/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ControladorComponentes;
import Modelo.ModeloComponentes;

/**
 *
 * @author cindy
 */
public class PanelComponentesProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistroProducto
     */
    public PanelComponentesProducto() {
        initComponents();
        
          ModeloComponentes modelo = new ModeloComponentes(this);
    
        ControladorComponentes controlador = new ControladorComponentes(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtDescripcionOficial = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCodigoBarras = new javax.swing.JTextField();
        cmbReceta = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JPanel();
        btnguardar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        btncancelar = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JPanel();
        Generador = new javax.swing.JLabel();
        txtInfBasica = new javax.swing.JTextField();
        txtComponentes = new javax.swing.JTextField();
        txtNombreAlt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CActivo = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(850, 655));

        fondoPanel.setBackground(new java.awt.Color(28, 95, 118));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        fondoPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COMPONENTES PRODUCTOS");
        fondoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 850, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FARMACIA");
        fondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Descripción Oficial* :");
        fondoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 160, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripción:");
        fondoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 160, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Código de Barras* :");
        fondoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 160, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("¿Se requiere receta?:");
        fondoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Activo:");
        fondoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        txtDescripcionOficial.setBackground(new java.awt.Color(75, 128, 146));
        txtDescripcionOficial.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDescripcionOficial.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcionOficial.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDescripcionOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionOficialActionPerformed(evt);
            }
        });
        fondoPanel.add(txtDescripcionOficial, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 230, -1));

        txtDescripcion.setBackground(new java.awt.Color(75, 128, 146));
        txtDescripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        fondoPanel.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 230, -1));

        txtCodigoBarras.setBackground(new java.awt.Color(75, 128, 146));
        txtCodigoBarras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCodigoBarras.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoBarras.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasActionPerformed(evt);
            }
        });
        fondoPanel.add(txtCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 230, -1));

        cmbReceta.setBackground(new java.awt.Color(75, 128, 146));
        cmbReceta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cmbReceta.setForeground(new java.awt.Color(255, 255, 255));
        cmbReceta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        fondoPanel.add(cmbReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 110, -1));

        btnGuardar.setBackground(new java.awt.Color(75, 128, 146));
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnguardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnguardar.setText("Guardar");
        btnGuardar.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        fondoPanel.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 110, 30));

        btnCancelar.setBackground(new java.awt.Color(75, 128, 146));
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("Cancelar");
        btnCancelar.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        fondoPanel.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 110, 30));

        btnGenerar.setBackground(new java.awt.Color(75, 128, 146));
        btnGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Generador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Generador.setForeground(new java.awt.Color(255, 255, 255));
        Generador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Generador.setLabelFor(btnSalir);
        Generador.setText("Generar");
        btnGenerar.add(Generador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        fondoPanel.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 385, 110, 30));

        txtInfBasica.setBackground(new java.awt.Color(75, 128, 146));
        txtInfBasica.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtInfBasica.setForeground(new java.awt.Color(255, 255, 255));
        txtInfBasica.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInfBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInfBasicaActionPerformed(evt);
            }
        });
        fondoPanel.add(txtInfBasica, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 170, 60));

        txtComponentes.setBackground(new java.awt.Color(75, 128, 146));
        txtComponentes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtComponentes.setForeground(new java.awt.Color(255, 255, 255));
        txtComponentes.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 170, 60));

        txtNombreAlt.setBackground(new java.awt.Color(75, 128, 146));
        txtNombreAlt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombreAlt.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreAlt.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombreAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAltActionPerformed(evt);
            }
        });
        fondoPanel.add(txtNombreAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 170, 60));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Información Básica");
        fondoPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 170, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Componentes");
        fondoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 170, -1));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nombre Alternativo");
        fondoPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 170, -1));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("(*) Campos Obligatorios");
        fondoPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 840, 20));

        CActivo.setBackground(new java.awt.Color(75, 128, 146));
        CActivo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        CActivo.setForeground(new java.awt.Color(255, 255, 255));
        CActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        fondoPanel.add(CActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAltActionPerformed

    private void txtDescripcionOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionOficialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionOficialActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarrasActionPerformed

    private void txtInfBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfBasicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfBasicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CActivo;
    public javax.swing.JLabel Generador;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnGenerar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnSalir;
    public javax.swing.JLabel btncancelar;
    public javax.swing.JLabel btnguardar;
    public javax.swing.JComboBox<String> cmbReceta;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtCodigoBarras;
    public javax.swing.JTextField txtComponentes;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtDescripcionOficial;
    public javax.swing.JTextField txtInfBasica;
    public javax.swing.JTextField txtNombreAlt;
    // End of variables declaration//GEN-END:variables

public void setControlador(ControladorComponentes controlador) {
        btnCancelar.addMouseListener(controlador);
        btnguardar.addMouseListener(controlador);
    }
}
