/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ControladorInventario;
import Modelo.ModeloInventario;

/**
 *
 * @author cindy
 */
public class PanelInventario extends javax.swing.JPanel {

    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        initComponents();

        ModeloInventario modelo = new ModeloInventario(this);
        ControladorInventario controlador = new ControladorInventario(modelo);

        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        marcaAgua = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        btnRegistroInventario = new javax.swing.JPanel();
        registroInventario = new javax.swing.JLabel();
        btnRegistroVenta = new javax.swing.JPanel();
        registroVenta = new javax.swing.JLabel();
        tblTablaInventario = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        separador = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(850, 700));

        fondoPanel.setBackground(new java.awt.Color(28, 95, 118));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("INVENTARIO");
        titulo.setPreferredSize(new java.awt.Dimension(302, 29));
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 850, -1));

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        fondoPanel.add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        fondoPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        btnRegistroInventario.setBackground(new java.awt.Color(75, 128, 146));
        btnRegistroInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistroInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroInventario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        registroInventario.setForeground(new java.awt.Color(255, 255, 255));
        registroInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroInventario.setText("Mostrar Registro Inventario");
        registroInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroInventario.add(registroInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 5, 200, 20));

        fondoPanel.add(btnRegistroInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, 30));

        btnRegistroVenta.setBackground(new java.awt.Color(75, 128, 146));
        btnRegistroVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistroVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroVenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        registroVenta.setForeground(new java.awt.Color(255, 255, 255));
        registroVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroVenta.setText("Mostrar Registro Ventas");
        registroVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroVenta.add(registroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 5, 200, 20));

        fondoPanel.add(btnRegistroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 210, 30));

        tblInventario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblInventario.setGridColor(new java.awt.Color(23, 75, 93));
        tblInventario.setShowGrid(false);
        tblTablaInventario.setViewportView(tblInventario);

        fondoPanel.add(tblTablaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 670, 260));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnRegistroInventario;
    public javax.swing.JPanel btnRegistroVenta;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JLabel registroInventario;
    private javax.swing.JLabel registroVenta;
    private javax.swing.JLabel salir;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    public javax.swing.JTable tblInventario;
    private javax.swing.JScrollPane tblTablaInventario;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorInventario controlador) {
        btnRegistroInventario.addMouseListener(controlador);
        btnRegistroVenta.addMouseListener(controlador);
    }
}
