/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ControladorProducto;
import Modelo.ModeloProducto;

/**
 *
 * @author cindy
 */
public class PanelProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelProducto
     */
    public PanelProducto() {
        initComponents();

        ModeloProducto modelo = new ModeloProducto(this);
        ControladorProducto controlador = new ControladorProducto(modelo);

        labelIDProducto.setVisible(false);
        txtIdProducto.setVisible(false);
        btnActualizar.setVisible(false);
        btnEliminar.setVisible(false);
        labelBuscarP.setVisible(false);
        txtCodigoBarrasP.setVisible(false);
        txtNombreProductoB.setVisible(false);
        labelNombreP.setVisible(false);
        btnBuscar.setVisible(false);
        labelCodigoBar.setVisible(false);

        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        marcaAgua = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelIDProducto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        txtNombreProducto = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCodigoBarras = new javax.swing.JTextField();
        txtFechaFabricacion = new javax.swing.JTextField();
        btnSalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        boxReceta = new javax.swing.JComboBox<>();
        boxActivo = new javax.swing.JComboBox<>();
        labelNombreP = new javax.swing.JLabel();
        txtNombreProductoB = new javax.swing.JTextField();
        labelCodigoBar = new javax.swing.JLabel();
        txtCodigoBarrasP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNombreAlterno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNumeroLote = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        labelBuscarP = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();

        fondoPanel.setBackground(new java.awt.Color(28, 95, 118));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("REGISTRO PRODUCTO");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, -1));

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        fondoPanel.add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre Producto:");
        fondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, 20));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Descripción:");
        fondoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        labelIDProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelIDProducto.setForeground(new java.awt.Color(255, 255, 255));
        labelIDProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIDProducto.setText("ID Producto");
        fondoPanel.add(labelIDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 100, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Código de Barras");
        fondoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Requiere receta:");
        fondoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 323, 120, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Activo:");
        fondoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 50, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Fecha Fabricación:");
        fondoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 140, 20));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        txtNombreProducto.setBackground(new java.awt.Color(75, 128, 146));
        txtNombreProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreProducto.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 270, -1));

        txtDescripcion.setBackground(new java.awt.Color(75, 128, 146));
        txtDescripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDescripcion.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 420, 80));

        txtCodigoBarras.setBackground(new java.awt.Color(75, 128, 146));
        txtCodigoBarras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCodigoBarras.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoBarras.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 391, 310, 20));

        txtFechaFabricacion.setBackground(new java.awt.Color(75, 128, 146));
        txtFechaFabricacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFechaFabricacion.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaFabricacion.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtFechaFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 120, -1));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        fondoPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        btnActualizar.setBackground(new java.awt.Color(75, 128, 146));
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Actualizar");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        fondoPanel.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 90, 30));

        btnAgregar.setBackground(new java.awt.Color(75, 128, 146));
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Agregar");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        fondoPanel.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 90, 30));

        btnEliminar.setBackground(new java.awt.Color(75, 128, 146));
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Limpiar");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        fondoPanel.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 90, 30));

        btnBuscar.setBackground(new java.awt.Color(75, 128, 146));
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Buscar");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        fondoPanel.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 90, 30));

        boxReceta.setBackground(new java.awt.Color(75, 128, 146));
        boxReceta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        boxReceta.setForeground(new java.awt.Color(255, 255, 255));
        boxReceta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "SI", "NO" }));
        boxReceta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoPanel.add(boxReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 80, -1));

        boxActivo.setBackground(new java.awt.Color(75, 128, 146));
        boxActivo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        boxActivo.setForeground(new java.awt.Color(255, 255, 255));
        boxActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        boxActivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActivoActionPerformed(evt);
            }
        });
        fondoPanel.add(boxActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 80, -1));

        labelNombreP.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelNombreP.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreP.setText("Nombre Producto");
        fondoPanel.add(labelNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 210, 20));

        txtNombreProductoB.setBackground(new java.awt.Color(75, 128, 146));
        txtNombreProductoB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombreProductoB.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreProductoB.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtNombreProductoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 210, -1));

        labelCodigoBar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelCodigoBar.setForeground(new java.awt.Color(255, 255, 255));
        labelCodigoBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCodigoBar.setText("Código de Barras");
        fondoPanel.add(labelCodigoBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 190, -1));

        txtCodigoBarrasP.setBackground(new java.awt.Color(75, 128, 146));
        txtCodigoBarrasP.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCodigoBarrasP.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoBarrasP.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtCodigoBarrasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 190, -1));

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Nombre Alternativo:");
        fondoPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 150, -1));

        txtNombreAlterno.setBackground(new java.awt.Color(75, 128, 146));
        txtNombreAlterno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombreAlterno.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreAlterno.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtNombreAlterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 270, -1));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Número Lote:");
        fondoPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 110, -1));

        txtNumeroLote.setBackground(new java.awt.Color(75, 128, 146));
        txtNumeroLote.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNumeroLote.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroLote.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtNumeroLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 80, -1));

        txtCantidad.setBackground(new java.awt.Color(75, 128, 146));
        txtCantidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        fondoPanel.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 80, -1));

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Cantidad:");
        fondoPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 110, -1));

        txtPrecioCompra.setBackground(new java.awt.Color(75, 128, 146));
        txtPrecioCompra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtPrecioCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioCompra.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCompraActionPerformed(evt);
            }
        });
        fondoPanel.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 80, -1));

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Precio Compra:");
        fondoPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 120, -1));

        txtPrecioVenta.setBackground(new java.awt.Color(75, 128, 146));
        txtPrecioVenta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtPrecioVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioVenta.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 80, -1));

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Precio Venta:");
        fondoPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 130, -1));

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Fecha Vencimiento:");
        fondoPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 150, -1));

        txtFechaVencimiento.setBackground(new java.awt.Color(75, 128, 146));
        txtFechaVencimiento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFechaVencimiento.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaVencimiento.setCaretColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 120, -1));

        labelBuscarP.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelBuscarP.setForeground(new java.awt.Color(255, 255, 255));
        labelBuscarP.setText("BUSCAR PRODUCTO");
        fondoPanel.add(labelBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, 20));

        txtIdProducto.setBackground(new java.awt.Color(75, 128, 146));
        txtIdProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCompraActionPerformed

    private void boxActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxActivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxActivo;
    public javax.swing.JComboBox<String> boxReceta;
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnAgregar;
    public javax.swing.JPanel btnBuscar;
    public javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelBuscarP;
    private javax.swing.JLabel labelCodigoBar;
    public javax.swing.JLabel labelIDProducto;
    private javax.swing.JLabel labelNombreP;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtCodigoBarras;
    public javax.swing.JTextField txtCodigoBarrasP;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtFechaFabricacion;
    public javax.swing.JTextField txtFechaVencimiento;
    public javax.swing.JTextField txtIdProducto;
    public javax.swing.JTextField txtNombreAlterno;
    public javax.swing.JTextField txtNombreProducto;
    public javax.swing.JTextField txtNombreProductoB;
    public javax.swing.JTextField txtNumeroLote;
    public javax.swing.JTextField txtPrecioCompra;
    public javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorProducto controlador) {
        btnAgregar.addMouseListener(controlador);
        btnBuscar.addMouseListener(controlador);
        btnActualizar.addMouseListener(controlador);
        btnEliminar.addMouseListener(controlador);
    }
}
