/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.ControladorVistaVendedor;
import Modelo.ModeloVistaVendedor;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author cindy
 */
public class VistaVendedor extends javax.swing.JFrame {

    /**
     * Creates new form VistaVendedor
     */
    public VistaVendedor() {
        initComponents();

        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagen/Pill Icon MT 1-100.png"));
        setIconImage(icono);

        ModeloVistaVendedor modelo = new ModeloVistaVendedor(this);
        ControladorVistaVendedor controlador = new ControladorVistaVendedor(modelo);

        setControlador(controlador);

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        fondoPanel = new javax.swing.JPanel();
        marcaAgua = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        userCajero = new javax.swing.JLabel();
        bienvenida = new javax.swing.JLabel();
        btnVentas = new javax.swing.JPanel();
        ventas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        clientes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        btnRegresar = new javax.swing.JPanel();
        regresar = new javax.swing.JLabel();
        fondoIzquierda = new javax.swing.JLabel();
        contenedorFondo = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        fondoPanel.add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, -1));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Pill Green MT 3 150x150.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        userCajero.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        userCajero.setForeground(new java.awt.Color(255, 255, 255));
        userCajero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCajero.setText("VENDEDOR");
        fondoPanel.add(userCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 350, 40));

        bienvenida.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenida.setText("Bienvenido");
        fondoPanel.add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 350, -1));

        btnVentas.setBackground(new java.awt.Color(75, 128, 146));
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ventas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ventas.setForeground(new java.awt.Color(255, 255, 255));
        ventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventas.setText("   Ventas");
        ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.add(ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("🛒");
        btnVentas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 20, 30));

        fondoPanel.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 210, 30));

        btnClientes.setBackground(new java.awt.Color(75, 128, 146));
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        clientes.setForeground(new java.awt.Color(255, 255, 255));
        clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientes.setText("  Clientes");
        btnClientes.add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("💁");
        btnClientes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 20, 30));

        fondoPanel.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 210, 30));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        fondoPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 30, 30));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 310, -1));

        btnRegresar.setBackground(new java.awt.Color(75, 128, 146));
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar.setText("Regresar");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 100, 20));

        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 110, 30));

        fondoIzquierda.setBackground(new java.awt.Color(23, 75, 93));
        fondoIzquierda.setOpaque(true);
        fondoPanel.add(fondoIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 700));

        contenedorFondo.setBackground(new java.awt.Color(28, 95, 118));
        contenedorFondo.setPreferredSize(new java.awt.Dimension(850, 655));

        javax.swing.GroupLayout contenedorFondoLayout = new javax.swing.GroupLayout(contenedorFondo);
        contenedorFondo.setLayout(contenedorFondoLayout);
        contenedorFondoLayout.setHorizontalGroup(
            contenedorFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        contenedorFondoLayout.setVerticalGroup(
            contenedorFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        fondoPanel.add(contenedorFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 860, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenida;
    public javax.swing.JPanel btnClientes;
    public javax.swing.JPanel btnRegresar;
    private javax.swing.JPanel btnSalir;
    public javax.swing.JPanel btnVentas;
    private javax.swing.JLabel clientes;
    public javax.swing.JPanel contenedorFondo;
    private javax.swing.JLabel fondoIzquierda;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JLabel regresar;
    private javax.swing.JLabel salir;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel userCajero;
    private javax.swing.JLabel ventas;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorVistaVendedor controlador) {
        btnRegresar.addMouseListener(controlador);
        btnClientes.addMouseListener(controlador);
        btnVentas.addMouseListener(controlador);
    }
}
