/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.ControladorVistaAdmin;
import Modelo.ModeloVistaAdmin;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author cindy
 */
public class VistaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin() {
        initComponents();

        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagen/Pill Icon MT 1-100.png"));
        setIconImage(icono);

        ModeloVistaAdmin modelo = new ModeloVistaAdmin(this);
        ControladorVistaAdmin controlador = new ControladorVistaAdmin(modelo);

        setControlador(controlador);
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        marcaAgua = new javax.swing.JLabel();
        bienvenida = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        userAdmin = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        btnProductos = new javax.swing.JPanel();
        productos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGestionInventario = new javax.swing.JPanel();
        inventario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JPanel();
        reportes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistroUsuarios = new javax.swing.JPanel();
        usuarios = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnComponentesProductos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JPanel();
        regresar = new javax.swing.JLabel();
        fondoIzquierda = new javax.swing.JLabel();
        contenedorFondo = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fondoPanel.setPreferredSize(new java.awt.Dimension(1200, 700));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        fondoPanel.add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, -1));

        bienvenida.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenida.setText("Bienvenido");
        fondoPanel.add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 350, -1));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Pill Red MT 2 150x150.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        userAdmin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        userAdmin.setForeground(new java.awt.Color(255, 255, 255));
        userAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userAdmin.setText("ADMIN");
        fondoPanel.add(userAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 350, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 310, -1));

        btnProductos.setBackground(new java.awt.Color(75, 128, 146));
        btnProductos.setForeground(new java.awt.Color(51, 51, 51));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnProductosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos.setBackground(new java.awt.Color(255, 255, 255));
        productos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productos.setForeground(new java.awt.Color(255, 255, 255));
        productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos.setText("   Productos");
        btnProductos.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("📦");
        jLabel2.setToolTipText("");
        btnProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 20, 30));

        fondoPanel.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 210, 30));

        btnGestionInventario.setBackground(new java.awt.Color(75, 128, 146));
        btnGestionInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        inventario.setForeground(new java.awt.Color(255, 255, 255));
        inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventario.setText("   Gestión Inventario");
        btnGestionInventario.add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("📂");
        btnGestionInventario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -4, 20, 40));

        fondoPanel.add(btnGestionInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 210, 30));

        btnReportes.setBackground(new java.awt.Color(75, 128, 146));
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportes.setText("      Reportes");
        btnReportes.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("📝");
        btnReportes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, -4, 20, 40));

        fondoPanel.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 210, 30));

        btnRegistroUsuarios.setBackground(new java.awt.Color(75, 128, 146));
        btnRegistroUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        usuarios.setForeground(new java.awt.Color(255, 255, 255));
        usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarios.setText("   Registro Usuarios");
        btnRegistroUsuarios.add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("👤");
        btnRegistroUsuarios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        fondoPanel.add(btnRegistroUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 210, 30));

        btnComponentesProductos.setBackground(new java.awt.Color(75, 128, 146));
        btnComponentesProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComponentesProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("   Componentes Productos");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComponentesProductos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("🎲");
        btnComponentesProductos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 70, 30));

        fondoPanel.add(btnComponentesProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 210, 30));

        btnRegresar.setBackground(new java.awt.Color(75, 128, 146));
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar.setText("Regresar");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 100, 30));

        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 110, 30));

        fondoIzquierda.setBackground(new java.awt.Color(23, 75, 93));
        fondoIzquierda.setOpaque(true);
        fondoPanel.add(fondoIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 700));

        contenedorFondo.setBackground(new java.awt.Color(28, 95, 118));
        contenedorFondo.setPreferredSize(new java.awt.Dimension(850, 655));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setMinimumSize(new java.awt.Dimension(30, 27));
        btnSalir.setPreferredSize(new java.awt.Dimension(30, 27));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        javax.swing.GroupLayout contenedorFondoLayout = new javax.swing.GroupLayout(contenedorFondo);
        contenedorFondo.setLayout(contenedorFondoLayout);
        contenedorFondoLayout.setHorizontalGroup(
            contenedorFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorFondoLayout.createSequentialGroup()
                .addContainerGap(824, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contenedorFondoLayout.setVerticalGroup(
            contenedorFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(664, Short.MAX_VALUE))
        );

        fondoPanel.add(contenedorFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 860, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        fondoPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnProductosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosAncestorAdded

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenida;
    public javax.swing.JPanel btnComponentesProductos;
    public javax.swing.JPanel btnGestionInventario;
    public javax.swing.JPanel btnProductos;
    public javax.swing.JPanel btnRegistroUsuarios;
    public javax.swing.JPanel btnRegresar;
    public javax.swing.JPanel btnReportes;
    private javax.swing.JPanel btnSalir;
    public javax.swing.JPanel contenedorFondo;
    private javax.swing.JLabel fondoIzquierda;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JLabel productos;
    private javax.swing.JLabel regresar;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel salir;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel userAdmin;
    private javax.swing.JLabel usuarios;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorVistaAdmin controlador) {
        btnRegresar.addMouseListener(controlador);
        btnProductos.addMouseListener(controlador);
        btnGestionInventario.addMouseListener(controlador);
        btnReportes.addMouseListener(controlador);
        btnRegistroUsuarios.addMouseListener(controlador);
        btnComponentesProductos.addMouseListener(controlador);
    }
}
