/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author cindy
 */
public class VistaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        userAdmin = new javax.swing.JLabel();
        btnProductos = new javax.swing.JPanel();
        productos = new javax.swing.JLabel();
        btnGestionInventario = new javax.swing.JPanel();
        inventario = new javax.swing.JLabel();
        btnReportes = new javax.swing.JPanel();
        reportes = new javax.swing.JLabel();
        btnRegistroUsuarios = new javax.swing.JPanel();
        usuarios = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        fondoIzquierda = new javax.swing.JLabel();
        fondoDerecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fondoPanel.setPreferredSize(new java.awt.Dimension(1200, 700));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("FARMACIA");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, -1));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/150 x 142.jpg"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, -1));

        userAdmin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        userAdmin.setForeground(new java.awt.Color(255, 255, 255));
        userAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userAdmin.setText("User: ADMIN");
        fondoPanel.add(userAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 230, 350, -1));

        btnProductos.setBackground(new java.awt.Color(75, 128, 146));
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        btnProductos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnProductosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productos.setForeground(new java.awt.Color(255, 255, 255));
        productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos.setText("Productos");
        btnProductos.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        fondoPanel.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 210, 30));

        btnGestionInventario.setBackground(new java.awt.Color(75, 128, 146));
        btnGestionInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        inventario.setForeground(new java.awt.Color(255, 255, 255));
        inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventario.setText("Gestión Inventario");
        btnGestionInventario.add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        fondoPanel.add(btnGestionInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 210, 30));

        btnReportes.setBackground(new java.awt.Color(75, 128, 146));
        btnReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportes.setText("Reportes");
        btnReportes.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        fondoPanel.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 210, 30));

        btnRegistroUsuarios.setBackground(new java.awt.Color(75, 128, 146));
        btnRegistroUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        usuarios.setForeground(new java.awt.Color(255, 255, 255));
        usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarios.setText("Registro Usuarios");
        btnRegistroUsuarios.add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        fondoPanel.add(btnRegistroUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 210, 30));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("Salir");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        fondoPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 110, 30));

        fondoIzquierda.setBackground(new java.awt.Color(23, 75, 93));
        fondoIzquierda.setOpaque(true);
        fondoPanel.add(fondoIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 700));

        fondoDerecha.setBackground(new java.awt.Color(28, 95, 118));
        fondoDerecha.setOpaque(true);
        fondoPanel.add(fondoDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 0, 860, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnProductosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosAncestorAdded

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0); 
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnGestionInventario;
    private javax.swing.JPanel btnProductos;
    private javax.swing.JPanel btnRegistroUsuarios;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel fondoDerecha;
    private javax.swing.JLabel fondoIzquierda;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel inventario;
    private javax.swing.JLabel productos;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel userAdmin;
    private javax.swing.JLabel usuarios;
    // End of variables declaration//GEN-END:variables
}
