/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controladores.ControladorVistaInicio;
import javax.swing.JFrame;
import modelos.ModeloVistaInicio;

/**
 *
 * @author cindy
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicio
     */
    public VistaInicio() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        ModeloVistaInicio modelo = new ModeloVistaInicio(this);
        ControladorVistaInicio controlador = new ControladorVistaInicio(modelo);
        
        setControlador(controlador);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        huella = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnAcceder = new javax.swing.JPanel();
        acceder = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fondoIzquierda = new javax.swing.JLabel();
        fondoDerecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fondoPanel.setBackground(new java.awt.Color(28, 95, 118));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("INICIO");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 410, -1));

        contraseña.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Contraseña:");
        fondoPanel.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 130, -1));

        usuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario: ");
        fondoPanel.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 80, 20));

        huella.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        huella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100 x 100.png"))); // NOI18N
        huella.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        huella.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fondoPanel.add(huella, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 410, 90));

        txtUsuario.setBackground(new java.awt.Color(75, 128, 146));
        txtUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setActionCommand("<Not Set>");
        txtUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUsuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setDoubleBuffered(true);
        txtUsuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 290, 30));

        txtContraseña.setBackground(new java.awt.Color(75, 128, 146));
        txtContraseña.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtContraseña.setCaretColor(new java.awt.Color(255, 255, 255));
        txtContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtContraseña.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtContraseña.setSelectionColor(new java.awt.Color(255, 255, 255));
        fondoPanel.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 290, 30));

        btnAcceder.setBackground(new java.awt.Color(75, 128, 146));
        btnAcceder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAcceder.setInheritsPopupMenu(true);
        btnAcceder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acceder.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        acceder.setForeground(new java.awt.Color(255, 255, 255));
        acceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceder.setText("Acceder");
        btnAcceder.add(acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 2, 110, 26));

        fondoPanel.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 110, 30));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        fondoPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 30, 30));

        fondoIzquierda.setBackground(new java.awt.Color(23, 75, 93));
        fondoIzquierda.setOpaque(true);
        fondoPanel.add(fondoIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 408, 480));

        fondoDerecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/600 x 568.jpg"))); // NOI18N
        fondoPanel.add(fondoDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 450, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0); 
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acceder;
    public javax.swing.JPanel btnAcceder;
    public javax.swing.JPanel btnSalir;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel fondoDerecha;
    private javax.swing.JLabel fondoIzquierda;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel huella;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

public void setControlador(ControladorVistaInicio controlador){
    
    btnAcceder.addMouseListener(controlador);
    
}


}